### PR TITLE
Add Portuguese translation

### PR DESCRIPTION
**Pull request by hugok79**
Add the portuguese language translation

### CODE REVIEW

**Comment by SMillerDev** [comment]
Which portuguese is this?

**Comment by hugok79** [comment]
> Which portuguese is this?

Portugal lang code = **pt** or **pt-PT**

**Portuguese** is the only official language that exists and the one spoken in **Portugal**
However, there are other variants such as Brazilian Portuguese **pt-BR**

For instance: http://www.lingoes.net/en/translator/langcode.htm

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @hugok79!

**Comment by hugok79** [comment]
If you want I can change it to **pt-PT**

Sometimes some translators or programmers/developers mistakenly add the Brazilian Portuguese as **pt** "lang code" which is not the case here in **hombebrew.sh**. As such and so that this does not happen there is also pt-PT "lang code" for that purpose.

**Pull request merged**
