### PR TITLE
Fixing the Kurdish language code

### PR DESCRIPTION
**Pull request by rawandahmad698**
:)

### CODE REVIEW

**Comment by maxim-belkin** [comment]
Question: English language is abbreviated as `en` -- I wonder if this means that we're using ISO 639-1 and Kurdish language should be `ku`?

**Comment by rawandahmad698** [comment]
> Question: English language is abbreviated as `en` -- I wonder if this means that we're using ISO 639-1 and Kurdish language should be `ku`?

You're correct, but there is two dialects, Kurmanji and Central Kurdish which are often confused, I'm using the ISO 639-2 language code (and to locals in my city, kur best defines Central Kurdish)

**Comment by maxim-belkin** [comment]
Sounds good!

**Review by maxim-belkin — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Thanks @rawandahmad698!

**Pull request merged**
