### PR TITLE
fix(install): add additinal installation steps

### PR DESCRIPTION
**Pull request by olegKusov**
изображение
Added additional installation steps following #721

### CODE REVIEW

**Comment by Bo98** [comment]
The problem with putting the commands here is that the one here only applies to people using zsh on arm64 macOS. A different command is needed for Intel macOS and Linux, as well as for other shells that are not `zsh`.

The installer script automatically determines which command is the appropriate one. Maybe it should be clearer to look out for that?

**Comment by Rylan12** [comment]
Alternatively, this could be put in [Common Issue](https://docs.brew.sh/Common-Issues) or the [FAQ](https://docs.brew.sh/FAQ)

**Comment by olegKusov** [comment]
> 
> 
> The problem with putting the commands here is that the one you've put here only applies to people using zsh on arm64 macOS. A different command is needed for Intel macOS and Linux, as well as for other shells that are not `zsh`.
> 
> The installer script automatically determines which command is the appropriate one. Maybe it should be clearer to look out for that?

I understand it. The problem is that people don't look at terminal after installation process is done. Maybe it's better to add some attention label on website or do not finish installation script until user read info about additional steps and then type "yes" .

**Comment by MikeMcQuaid** [comment]
Passing on this, it makes the homepage pretty ugly and I don't see this being a common problem.

**Pull request closed without merging**
