### PR TITLE
Git ignored CNAME

### PR DESCRIPTION
**Pull request by RDIL**

### CODE REVIEW

**Comment by reitermarkus** [comment]
What does the CNAME have to do with it being static?

**Comment by RDIL** [comment]
Well we don’t want the CNAME to change unless it is absolutely needed

**Comment by MikeMcQuaid** [comment]
This file needs to be checked into Git so should not be ignored. Please always provide descriptions for PRs in future.

**Comment by RDIL** [comment]
👍 got it.

**Pull request closed without merging**
