### PR TITLE
Optimize all SVGs

### PR DESCRIPTION
**Pull request by colindean**
Done with:

    svgo --multipass assets/img/*.svg

> Dad: Europe has some nice golf courses.
>
> Colin: Oh, I'm doing more golfing than you know.

### CODE REVIEW

**Comment by colindean** [comment]
It looks like imgbot _was_ configured but needs its permissions reupped at https://github.com/apps/imgbot/installations/1093259. I don't have perms to do it.

**Comment by MikeMcQuaid** [comment]
@colindean hmm, I don't see anything about permissions there.

**Comment by colindean** [comment]
When I go to https://github.com/apps/imgbot, I click on CONFIGURE and am taken to https://github.com/apps/imgbot/installations/new. On that page, I click the CONFIGURE next to Homebrew and it takes me to https://github.com/apps/imgbot/installations/1093259. I choose the Only Selected Repositories radio button-- the only option-- and choose the brew.sh repo, which has _Request_ next to it. When I click UPDATE ACCESS, I see this error message:

> You do not have permission to modify this app on Homebrew. Please contact an Organization Owner.

**Comment by MikeMcQuaid** [comment]
@colindean I've done that and got no warnings. Maybe it'll work now 🤞🏻

**Pull request merged**
