### PR TITLE
Indonesian translation

### PR DESCRIPTION
**Pull request by leapofazzam123**
An Indonesian translation for the brew.sh website

### CODE REVIEW

**Comment by leapofazzam123** [comment]
> Please provide a better issue/pull request title and/or description!

Ok

**Comment by leapofazzam123** [comment]
Nvm transifex exists

**Comment by MikeMcQuaid** [comment]
@leapofazzam123 Happy to accept a PR here instead unless you'd prefer Transifex?

**Comment by leapofazzam123** [comment]
> @leapofazzam123 Happy to accept a PR here instead unless you'd prefer Transifex?

Yes, i want pr

**Comment by MikeMcQuaid** [comment]
Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @leapofazzam123!

**Pull request merged**
